{% set name = "lmfit" %}
{% set version = "1.3.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 73321e6b881f2f686235721a7dfc02af6bb0f030a25efeb66638f62b1c6053a1
build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - setuptools_scm
    - asteval >=0.9.22
    - numpy >=1.18
    - pip
    - python
    - scipy >=1.4
    - uncertainties >=3.0.1
  run:
    - asteval >=0.9.22
    - numpy >=1.18
    - python
    - scipy >=1.4
    - uncertainties >=3.0.1


about:
  home: "https://lmfit.github.io/lmfit-py/"
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: "Non-Linear Least Squares Minimization, with flexible Parameter settings, based on scipy.optimize, and with many additional classes and methods for curve fitting."
  doc_url: https://lmfit.github.io/lmfit-py/
  dev_url: https://github.com/lmfit/lmfit-py/

extra:
  recipe-maintainers:
    - https://github.com/gb119
