
name: Conda

on:
  push

# workflow_dispatch:        # Un comment line if you also want to trigger action manually

jobs:
  conda_deployment_with_new_tag:
    name: Conda deployment of package for platform ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v3.1.1
        with:
          python-version: "3.12"
          environment-file: env.yaml
          activate-environment: build
          auto-update-conda: true
          auto-activate-base: false
          show-channel-urls: true
      - name: Build and upload the conda packages
        uses: uibcdf/action-build-and-upload-conda-packages@HEAD
        with:
          meta_yaml_dir: .
          overwrite: true
          python-version: "3.12"
          user: phygbu
          label: main
          token: ${{ secrets.ANACONDA }} # Replace with the right name of your secret
